spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

logging:
  level:
    root: INFO
    com.apidesign: INFO
    org.hibernate.SQL: INFO

app:
  security:
    jwt:
      enabled: true
  validation:
    enabled: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
    enabled: true
    operations-sorter: method
    tags-sorter: alpha
