spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:oracle:thin:@prod-oracle-host:1521/FREEPDB1
    username: ${DB_USERNAME:system}
    password: ${DB_PASSWORD}
    hikari:
      minimum-idle: 10
      maximum-pool-size: 50
      connection-timeout: 60000
      idle-timeout: 900000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: validate  # Production must validate only
      format_sql: false # Don't format SQL in production
    show-sql: false

logging:
  level:
    root: WARN
    com.apidesign: INFO
  file:
    name: /var/log/order-management-system/application.log
    max-size: 10MB
    max-history: 30

springdoc:
  swagger-ui:
    enabled: false  # Disable Swagger UI in production for security


server:
  port: 8443
  ssl:
    enabled: true
    key-store: ${SSL_KEYSTORE_PATH}
    key-store-password: ${SSL_KEYSTORE_PASSWORD}
    key-store-type: PKCS12

