-- Persistent audit trail of failed requests (status >= 500 or uncaught exceptions).
-- Matches entity/ApplicationException.java column-for-column.
-- Idempotent: ORA-00955 (name already used) is logged and skipped.

SET SERVEROUTPUT ON;

BEGIN
  EXECUTE IMMEDIATE 'CREATE SEQUENCE APP_EXCEPTION_SEQ START WITH 1 INCREMENT BY 50 NOCACHE NOCYCLE';
  DBMS_OUTPUT.PUT_LINE('Created sequence APP_EXCEPTION_SEQ');
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -955 THEN DBMS_OUTPUT.PUT_LINE('Sequence APP_EXCEPTION_SEQ already exists, skipping');
    ELSE RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE APPLICATION_EXCEPTION (
        ID                  NUMBER(19)      NOT NULL,
        CORRELATION_ID      VARCHAR2(64),
        HTTP_METHOD         VARCHAR2(10),
        REQUEST_PATH        VARCHAR2(512),
        QUERY_STRING        VARCHAR2(2048),
        REQUEST_BODY        CLOB,
        RESPONSE_STATUS     NUMBER(10),
        EXCEPTION_CLASS     VARCHAR2(256),
        EXCEPTION_MESSAGE   CLOB,
        STACK_TRACE         CLOB,
        USER_ID             VARCHAR2(128),
        CLIENT_IP           VARCHAR2(64),
        DURATION_MS         NUMBER(19),
        CREATED_AT          TIMESTAMP(6)    NOT NULL,
        UPDATED_AT          TIMESTAMP(6),
        CREATED_BY          VARCHAR2(100),
        UPDATED_BY          VARCHAR2(100),
        CONSTRAINT PK_APPLICATION_EXCEPTION PRIMARY KEY (ID)
    )
  ]';
  DBMS_OUTPUT.PUT_LINE('Created table APPLICATION_EXCEPTION');
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -955 THEN DBMS_OUTPUT.PUT_LINE('Table APPLICATION_EXCEPTION already exists, skipping');
    ELSE RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX IDX_APP_EXC_CORRELATION ON APPLICATION_EXCEPTION (CORRELATION_ID)';
  DBMS_OUTPUT.PUT_LINE('Created index IDX_APP_EXC_CORRELATION');
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -955 THEN DBMS_OUTPUT.PUT_LINE('Index IDX_APP_EXC_CORRELATION already exists, skipping');
    ELSE RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX IDX_APP_EXC_CREATED_AT ON APPLICATION_EXCEPTION (CREATED_AT)';
  DBMS_OUTPUT.PUT_LINE('Created index IDX_APP_EXC_CREATED_AT');
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -955 THEN DBMS_OUTPUT.PUT_LINE('Index IDX_APP_EXC_CREATED_AT already exists, skipping');
    ELSE RAISE; END IF;
END;
/
