-- Refresh tokens with rotation + family-tracking for reuse detection.
-- See entity/RefreshToken.java and service/AuthService.refresh(...).

CREATE SEQUENCE REFRESH_TOKEN_SEQ START WITH 1 INCREMENT BY 50 NOCACHE NOCYCLE;

CREATE TABLE REFRESH_TOKENS (
    ID                  NUMBER(19)      NOT NULL,
    TOKEN_HASH          VARCHAR2(64)    NOT NULL,
    USER_ID             NUMBER(19)      NOT NULL,
    EXPIRES_AT          TIMESTAMP(6)    NOT NULL,
    REVOKED             NUMBER(1)       DEFAULT 0 NOT NULL,
    REPLACED_BY_HASH    VARCHAR2(64),
    FAMILY_ID           VARCHAR2(36)    NOT NULL,
    CREATED_AT          TIMESTAMP(6)    NOT NULL,
    UPDATED_AT          TIMESTAMP(6),
    CREATED_BY          VARCHAR2(100),
    UPDATED_BY          VARCHAR2(100),
    CONSTRAINT PK_REFRESH_TOKENS PRIMARY KEY (ID),
    CONSTRAINT UK_REFRESH_TOKEN_HASH UNIQUE (TOKEN_HASH),
    CONSTRAINT FK_REFRESH_TOKEN_USER FOREIGN KEY (USER_ID) REFERENCES "USERS" (ID)
);

CREATE INDEX IDX_REFRESH_TOKEN_FAMILY ON REFRESH_TOKENS (FAMILY_ID);
CREATE INDEX IDX_REFRESH_TOKEN_USER ON REFRESH_TOKENS (USER_ID);
