-- Order saga control-plane. One row per saga execution; tracks state transitions and
-- carries an append-only JSON compensation log for post-mortem diagnostics.
-- Idempotent: ORA-00955 (name already used) is logged and skipped, same pattern as V1-V5.

SET SERVEROUTPUT ON;

BEGIN
  EXECUTE IMMEDIATE 'CREATE SEQUENCE ORDER_SAGA_SEQ START WITH 1 INCREMENT BY 50 NOCACHE NOCYCLE';
  DBMS_OUTPUT.PUT_LINE('Created sequence ORDER_SAGA_SEQ');
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -955 THEN DBMS_OUTPUT.PUT_LINE('Sequence ORDER_SAGA_SEQ already exists, skipping');
    ELSE RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE ORDER_SAGA (
        ID                  NUMBER(19)      NOT NULL,
        SAGA_ID             VARCHAR2(64)    NOT NULL,
        ORDER_ID            NUMBER(19)      NOT NULL,
        CURRENT_STATE       VARCHAR2(50)    NOT NULL,
        CURRENT_STEP        VARCHAR2(50),
        ERROR_MESSAGE       VARCHAR2(2000),
        COMPENSATION_LOG    CLOB,
        CREATED_AT          TIMESTAMP(6)    NOT NULL,
        UPDATED_AT          TIMESTAMP(6),
        CREATED_BY          VARCHAR2(100),
        UPDATED_BY          VARCHAR2(100),
        CONSTRAINT PK_ORDER_SAGA PRIMARY KEY (ID)
    )
  ]';
  DBMS_OUTPUT.PUT_LINE('Created table ORDER_SAGA');
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -955 THEN DBMS_OUTPUT.PUT_LINE('Table ORDER_SAGA already exists, skipping');
    ELSE RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX IDX_ORDER_SAGA_SAGA_ID ON ORDER_SAGA (SAGA_ID)';
  DBMS_OUTPUT.PUT_LINE('Created index IDX_ORDER_SAGA_SAGA_ID');
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -955 THEN DBMS_OUTPUT.PUT_LINE('Index IDX_ORDER_SAGA_SAGA_ID already exists, skipping');
    ELSE RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX IDX_ORDER_SAGA_ORDER_ID ON ORDER_SAGA (ORDER_ID)';
  DBMS_OUTPUT.PUT_LINE('Created index IDX_ORDER_SAGA_ORDER_ID');
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -955 THEN DBMS_OUTPUT.PUT_LINE('Index IDX_ORDER_SAGA_ORDER_ID already exists, skipping');
    ELSE RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX IDX_ORDER_SAGA_STATE ON ORDER_SAGA (CURRENT_STATE)';
  DBMS_OUTPUT.PUT_LINE('Created index IDX_ORDER_SAGA_STATE');
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -955 THEN DBMS_OUTPUT.PUT_LINE('Index IDX_ORDER_SAGA_STATE already exists, skipping');
    ELSE RAISE; END IF;
END;
/
