package com.apidesign.repository;

import com.apidesign.entity.User;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import java.util.Optional;

/**
 * User repository demonstrating different query approaches.
 *
 * Query Strategy Guide:
 * 1. DERIVED QUERIES: Simple, readable, generated by Spring Data from method name
 *    Best for: Single entity lookups, simple conditions
 * 2. JPQL QUERIES: Type-safe, portable, abstract over database
 *    Best for: Complex queries, joins, aggregations
 * 3. NATIVE SQL: Direct database access, highest performance
 *    Best for: Complex business queries, specific DB features
 */
@Repository
public interface UserRepository extends JpaRepository<User, Long> {

    /**
     * DERIVED QUERY: Spring Data generates SQL from method name.
     * Equivalent SQL: SELECT * FROM USERS WHERE EMAIL = ?
     *
     * When to use: Simple lookups by single property.
     * Performance: Good, Hibernate optimizes automatically.
     */
    Optional<User> findByEmail(String email);

    /**
     * DERIVED QUERY with multiple conditions.
     * Equivalent SQL: SELECT * FROM USERS WHERE FIRST_NAME = ? AND IS_ACTIVE = true
     */
    Optional<User> findByFirstNameAndIsActive(String firstName, Boolean isActive);

    /**
     * JPQL QUERY: Explicit query using Jakarta Query Language.
     * Benefits over derived queries:
     * - More control over query structure
     * - Better for complex queries
     * - Explicit documentation of query intent
     *
     * @param email the user's email
     * @return Optional containing user if found
     */
    @Query("SELECT u FROM User u WHERE LOWER(u.email) = LOWER(:email)")
    Optional<User> findByEmailIgnoreCase(@Param("email") String email);

    /**
     * JPQL QUERY with pagination for listing active users.
     * Demonstrates: Sorting, Filtering, Pagination
     *
     * Why Page instead of List:
     * - Includes total count for pagination UI
     * - Lazy loads data efficiently
     * - Handles large datasets gracefully
     *
     * @param isActive filter condition
     * @param pageable pagination info (page size, page number, sort)
     * @return Page of users
     */
    @Query("SELECT u FROM User u WHERE u.isActive = :isActive ORDER BY u.firstName, u.lastName")
    Page<User> findActiveUsers(@Param("isActive") Boolean isActive, Pageable pageable);

    /**
     * NATIVE SQL QUERY: Direct database access using SQL.
     * Use when:
     * - JPQL can't express the query efficiently
     * - Using database-specific functions
     * - Optimizing high-performance queries
     *
     * Limitations:
     * - Less portable across databases
     * - Manual result mapping
     *
     * @return native query result mapped to User entity
     */
    @Query(value = "SELECT * FROM USERS WHERE CREATED_AT > SYSDATE - 7 AND IS_ACTIVE = 1",
           nativeQuery = true)
    Page<User> findUsersCreatedInLastWeek(Pageable pageable);

    /**
     * Example: Check if user with email exists.
     * More efficient than findByEmail as it returns boolean instead of full entity.
     */
    boolean existsByEmail(String email);

    /**
     * JPQL Query with Join (explicit example for documentation).
     * Useful when you need related data in future enhancements.
     */
    @Query("SELECT COUNT(u) FROM User u WHERE u.isActive = true")
    long countActiveUsers();
}

